name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ["api-lambda"]

    steps:
      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2

      - name: Set up Docker Buildx      
        uses: crazy-max/ghaction-docker-buildx@v1      
        with:        
          version: latest 

      - name: Build container
        run: | 
          docker buildx build --platform linux/arm/v8 --tag test:v8 --file ci/Dockerfile.lambda